// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53MqqlqajxYv4xKVPkZix-EInbvLiwf4',
    appId: '1:1086086283040:web:c8177501989e14f0d1a145',
    messagingSenderId: '1086086283040',
    projectId: 'frim-1f51c',
    authDomain: 'frim-1f51c.firebaseapp.com',
    storageBucket: 'frim-1f51c.appspot.com',
    measurementId: 'G-BXVEPWTQFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mLDH-c8q_Bh5C3aUeQBlECxO1rLchz8',
    appId: '1:1086086283040:android:207dadbe86a8bbabd1a145',
    messagingSenderId: '1086086283040',
    projectId: 'frim-1f51c',
    storageBucket: 'frim-1f51c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qHL9-Ozu_aYUQZEJXXhYZ5lXcqa2v1A',
    appId: '1:1086086283040:ios:73d44d6b617de7a9d1a145',
    messagingSenderId: '1086086283040',
    projectId: 'frim-1f51c',
    storageBucket: 'frim-1f51c.appspot.com',
    iosClientId: '1086086283040-ak8kq3krd3pt17kido7ducbruen3tptg.apps.googleusercontent.com',
    iosBundleId: 'com.example.oua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2qHL9-Ozu_aYUQZEJXXhYZ5lXcqa2v1A',
    appId: '1:1086086283040:ios:7d922541380a11e5d1a145',
    messagingSenderId: '1086086283040',
    projectId: 'frim-1f51c',
    storageBucket: 'frim-1f51c.appspot.com',
    iosClientId: '1086086283040-s1kk9hp9r14fsnr0cd4u0613kt6edgfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.oua.RunnerTests',
  );
}
